config/routes.rb
# frozen-string-literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants, only: %i[index new create show] do
    resources :reviews, only: %i[create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
# frozen-string-literal: true

# Restaurant Class
class Restaurant < ApplicationRecord
  CATEGORIES = %w[chinese italian japanese french belgian].freeze
  has_many :reviews, dependent: :destroy
  validates :name, :address, presence: true
  validates :category, inclusion: { in: CATEGORIES,
                                    message: "%{value} is not a valid category" }
end

app/models/review.rb
# frozen-string-literal: true

# Review Class
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true, numericality: true, inclusion: { in: (0..5) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
# frozen-string-literal: true

# Restaurants Controller
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @review = Review.new
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category, :phone_number)
  end
end

app/controllers/reviews_controller.rb
# frozen-string-literal: true

# Reviews Controller
class ReviewsController < ApplicationController

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render 'restaurants/show'
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <!-- Add these line for detecting device width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1>All Restaurants</h1>

<%
=begin %>
<%= link_to 'Create a new Restaurant', new_restaurant_path, class: "btn btn-outline-secondary" %>
<ul class="list-group list-group-flush mt-3">
  <% @restaurants.each do |restaurant| %>
    <li class="list-group-item">
      <h5><%= link_to restaurant.name, restaurant_path(restaurant)%></h5>
      <p><%= restaurant.category %></p>
    </li>
  <% end %>
</ul>
<%
=end %>
<%= link_to 'Create a new Restaurant', new_restaurant_path, class: "btn btn-outline-secondary mb-3" %>
<div class="row row-cols-1 row-cols-md-3">
  <% @restaurants.each do |restaurant| %>
    <div class="col mb-4">
      <div class="card h-100">
        <div class="card-body">
          <h5 class="card-title"><%= restaurant.name %></h5>
          <h6 class="card-subtitle mb-2 text-muted"><%= restaurant.category %></h6>
          <%= link_to 'View details', restaurant_path(restaurant), class: "card-link" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/restaurants/new.html.erb
<div class="container col-lg-8">
  <h1>Create new restaurant</h1>
  <%= simple_form_for(@restaurant) do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :category, collection: Restaurant::CATEGORIES %>
    <%= f.input :phone_number %>
    <div class="d-flex justify-content-between">
      <%= f.submit class: 'btn btn-primary' %>
      <%= link_to 'Back to restaurants', restaurants_path, class: "btn btn-outline-secondary" %>
    </div>  <% end %>
</div>

app/views/restaurants/show.html.erb
<div class="container col-lg-8 mb-5">
  <h1><%= @restaurant.name %></h1>
  <p><strong>Address: </strong> <%= @restaurant.address%></p>
  <p><strong>Tel: </strong><%= @restaurant.phone_number %></p>
  <h4>Reviews</h4>
    <ul class="list-group mb-4">
      <% @restaurant.reviews.each do |review| %>
        <li class="list-group-item">
          <div class="d-flex justify-content-between">
            <span><%= review.content %></span>
            <span><%= '⭐' * review.rating%></span>
          </div>
        </li>
      <% end %>
    </ul>

  <h4>If you know this restaurant, leave your comment.</h4>
  <%= simple_form_for [@restaurant, @review] do |f| %>
    <%= f.input :content %>
    <%= f.input :rating, collection: 0..5 %>
    <!-- adds bootstrap button  -->
    <div class="d-flex justify-content-between">
      <%= f.submit class: 'btn btn-primary' %>
      <%= link_to 'Back to restaurants', restaurants_path, class: "btn btn-outline-secondary" %>
    </div>
  <% end %>
</div>